-- Add client-formula library fields to an existing IAHNUTR library.
-- Skip if you created the schema from the updated schema-ibmi.sql.

SET SCHEMA IAHNUTR;

ALTER TABLE CLIENT ADD COLUMN IS_DEFAULT SMALLINT NOT NULL DEFAULT 0;

INSERT INTO CLIENT (CODE, NAME, NOTES, IS_DEFAULT, ACTIVE)
SELECT 'DEFAULT', 'Default (general formulas)',
       'Owner for catalog formulas shared across clients', 1, 1
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM CLIENT WHERE CODE = 'DEFAULT');

ALTER TABLE FORMULA ADD COLUMN STATUS VARCHAR(16) NOT NULL DEFAULT 'OPTIMIZED';

ALTER TABLE FORMULA ALTER COLUMN OPTIMIZATION_TYPE DROP NOT NULL;
ALTER TABLE FORMULA ALTER COLUMN SOLVER_STATUS DROP NOT NULL;

ALTER TABLE FORMULA ADD CONSTRAINT CK_FORMULA_STATUS
    CHECK (STATUS IN ('OPTIMIZED', 'PREFIXED'));

ALTER TABLE FORMULA_INGREDIENT ADD COLUMN LAST_PRICE DECIMAL(18, 6) NOT NULL DEFAULT 0;

UPDATE FORMULA_INGREDIENT
   SET LAST_PRICE = PRICE_USED
 WHERE LAST_PRICE = 0;

UPDATE FORMULA
   SET CLIENT_ID = (SELECT CLIENT_ID FROM CLIENT WHERE CODE = 'DEFAULT')
 WHERE CLIENT_ID IS NULL;

ALTER TABLE FORMULA ALTER COLUMN CLIENT_ID SET NOT NULL;

CREATE INDEX IX_FORMULA_STATUS ON FORMULA (STATUS, CLIENT_ID);

CREATE TABLE CLIENT_FORMULAS_HDR (
    FORMULA_ID              BIGINT NOT NULL,
    CLIENT_ID               BIGINT NOT NULL,
    FORMULA_DESCRIPTION     VARCHAR(128) NOT NULL,
    LAST_PRICE              DECIMAL(18, 6),
    ANIMAL_ID               BIGINT NOT NULL,
    OPTIMIZATION_TECHNIQUE  VARCHAR(16),
    CONSTRAINT PK_CLTFMHDR PRIMARY KEY (FORMULA_ID),
    CONSTRAINT FK_CLTFMHDR_FORMULA FOREIGN KEY (FORMULA_ID) REFERENCES FORMULA (FORMULA_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CLTFMHDR_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
    CONSTRAINT FK_CLTFMHDR_ANIMAL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL_SPECIES (SPECIES_ID)
) FOR SYSTEM NAME CLTFMHDR;

CREATE INDEX IX_CLTFMHDR_CLIENT ON CLIENT_FORMULAS_HDR (CLIENT_ID, ANIMAL_ID);

INSERT INTO CLIENT_FORMULAS_HDR
    (FORMULA_ID, CLIENT_ID, FORMULA_DESCRIPTION, LAST_PRICE, ANIMAL_ID, OPTIMIZATION_TECHNIQUE)
SELECT F.FORMULA_ID, F.CLIENT_ID, F.NAME, COALESCE(F.COST_PER_KG, F.TOTAL_COST),
       F.SPECIES_ID, F.OPTIMIZATION_TYPE
FROM FORMULA F
WHERE NOT EXISTS (
    SELECT 1 FROM CLIENT_FORMULAS_HDR H WHERE H.FORMULA_ID = F.FORMULA_ID
);
