-- Add INGREDNUT to an existing IAHNUTR library and backfill the full matrix.
-- Skip if you created the schema from the updated schema-ibmi.sql.

SET SCHEMA IAHNUTR;

CREATE TABLE INGREDNUT (
    INGREDIENT_ID   BIGINT NOT NULL,
    NUTRIENT_ID     BIGINT NOT NULL,
    AMOUNT          DECIMAL(18, 8) NOT NULL DEFAULT 0,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_INGREDNUT PRIMARY KEY (INGREDIENT_ID, NUTRIENT_ID),
    CONSTRAINT FK_INGREDNUT_ING FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_INGREDNUT_NUT FOREIGN KEY (NUTRIENT_ID) REFERENCES NUTRIENT (NUTRIENT_ID) ON DELETE CASCADE
);

CREATE INDEX IX_INGREDNUT_NUT ON INGREDNUT (NUTRIENT_ID);

INSERT INTO INGREDNUT (INGREDIENT_ID, NUTRIENT_ID, AMOUNT)
SELECT I.INGREDIENT_ID, N.NUTRIENT_ID, 0
FROM INGREDIENT I
CROSS JOIN NUTRIENT N;

MERGE INTO INGREDNUT T
USING (
    SELECT INGREDIENT_ID, NUTRIENT_ID, AMOUNT
    FROM INGREDIENT_NUTRIENT
) S
ON T.INGREDIENT_ID = S.INGREDIENT_ID AND T.NUTRIENT_ID = S.NUTRIENT_ID
WHEN MATCHED THEN UPDATE SET AMOUNT = S.AMOUNT, UPDATED_AT = CURRENT_TIMESTAMP;
