-- IAH Nutrition schema for IBM i (Db2 for i 7.3+)
-- Run from STRSQL, Run SQL Scripts, or:
--   RUNSQLSTM SRCSTMF('/home/USER/iah-nutrition/schema-ibmi.sql') COMMIT(*NONE)
--
-- Creates library/schema IAHNUTR with unlimited ingredients, nutrients,
-- clients, animal requirements (species/age/other factors), and formulas.

CREATE SCHEMA IAHNUTR;

SET SCHEMA IAHNUTR;

CREATE TABLE NUTRIENT (
    NUTRIENT_ID     BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODE            VARCHAR(32) NOT NULL,
    NAME            VARCHAR(128) NOT NULL,
    UNIT            VARCHAR(32) NOT NULL,
    CATEGORY        VARCHAR(32),
    DESCRIPTION     VARCHAR(512),
    ACTIVE          SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_NUTRIENT PRIMARY KEY (NUTRIENT_ID),
    CONSTRAINT UQ_NUTRIENT_CODE UNIQUE (CODE)
);

CREATE TABLE INGREDIENT (
    INGREDIENT_ID   BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODE            VARCHAR(32) NOT NULL,
    NAME            VARCHAR(128) NOT NULL,
    CATEGORY        VARCHAR(64),
    PRICE           DECIMAL(18, 6) NOT NULL DEFAULT 0,
    PRICE_UNIT      VARCHAR(16) NOT NULL DEFAULT 'USD/kg',
    DRY_MATTER_PCT  DECIMAL(9, 4),
    DENSITY         DECIMAL(9, 4),
    MIN_INCLUSION   DECIMAL(9, 6) NOT NULL DEFAULT 0,
    MAX_INCLUSION   DECIMAL(9, 6) NOT NULL DEFAULT 1,
    QUADRATIC_COST  DECIMAL(18, 8) NOT NULL DEFAULT 0,
    SUPPLIER        VARCHAR(128),
    NOTES           VARCHAR(512),
    ACTIVE          SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_INGREDIENT PRIMARY KEY (INGREDIENT_ID),
    CONSTRAINT UQ_INGREDIENT_CODE UNIQUE (CODE)
);

-- One row for every ingredient x every nutrient. RPG REST keeps this full.
CREATE TABLE INGREDNUT (
    INGREDIENT_ID   BIGINT NOT NULL,
    NUTRIENT_ID     BIGINT NOT NULL,
    AMOUNT          DECIMAL(18, 8) NOT NULL DEFAULT 0,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_INGREDNUT PRIMARY KEY (INGREDIENT_ID, NUTRIENT_ID),
    CONSTRAINT FK_INGREDNUT_ING FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_INGREDNUT_NUT FOREIGN KEY (NUTRIENT_ID) REFERENCES NUTRIENT (NUTRIENT_ID) ON DELETE CASCADE
);

CREATE INDEX IX_INGREDNUT_NUT ON INGREDNUT (NUTRIENT_ID);

-- Compatibility view of the composition matrix.
CREATE VIEW INGREDIENT_NUTRIENT AS
SELECT INGREDIENT_ID, NUTRIENT_ID, AMOUNT
FROM INGREDNUT;

CREATE TABLE INGREDIENT_PRICE (
    PRICE_ID        BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    INGREDIENT_ID   BIGINT NOT NULL,
    PRICE           DECIMAL(18, 6) NOT NULL,
    PRICE_UNIT      VARCHAR(16) NOT NULL DEFAULT 'USD/kg',
    EFFECTIVE_DATE  DATE NOT NULL,
    SOURCE          VARCHAR(128),
    NOTES           VARCHAR(256),
    CONSTRAINT PK_ING_PRICE PRIMARY KEY (PRICE_ID),
    CONSTRAINT FK_INGPRICE_ING FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID) ON DELETE CASCADE
);

CREATE INDEX IX_INGPRICE_ING_DATE ON INGREDIENT_PRICE (INGREDIENT_ID, EFFECTIVE_DATE);

CREATE TABLE CLIENT (
    CLIENT_ID       BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODE            VARCHAR(32) NOT NULL,
    NAME            VARCHAR(128) NOT NULL,
    CONTACT_NAME    VARCHAR(128),
    PHONE           VARCHAR(32),
    EMAIL           VARCHAR(128),
    ADDRESS         VARCHAR(256),
    CITY            VARCHAR(64),
    STATE           VARCHAR(64),
    POSTAL_CODE     VARCHAR(16),
    COUNTRY         VARCHAR(64),
    NOTES           VARCHAR(512),
    ACTIVE          SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENT PRIMARY KEY (CLIENT_ID),
    CONSTRAINT UQ_CLIENT_CODE UNIQUE (CODE)
);

CREATE TABLE ANIMAL_SPECIES (
    SPECIES_ID      BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODE            VARCHAR(32) NOT NULL,
    NAME            VARCHAR(128) NOT NULL,
    DESCRIPTION     VARCHAR(512),
    ACTIVE          SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_SPECIES PRIMARY KEY (SPECIES_ID),
    CONSTRAINT UQ_SPECIES_CODE UNIQUE (CODE)
);

CREATE TABLE ANIMAL_STAGE (
    STAGE_ID        BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SPECIES_ID      BIGINT NOT NULL,
    CODE            VARCHAR(32) NOT NULL,
    NAME            VARCHAR(128) NOT NULL,
    AGE_MIN_DAYS    INTEGER,
    AGE_MAX_DAYS    INTEGER,
    WEIGHT_MIN_KG   DECIMAL(9, 3),
    WEIGHT_MAX_KG   DECIMAL(9, 3),
    DESCRIPTION     VARCHAR(512),
    ACTIVE          SMALLINT NOT NULL DEFAULT 1,
    CONSTRAINT PK_STAGE PRIMARY KEY (STAGE_ID),
    CONSTRAINT FK_STAGE_SPECIES FOREIGN KEY (SPECIES_ID) REFERENCES ANIMAL_SPECIES (SPECIES_ID),
    CONSTRAINT UQ_STAGE_SPECIES_CODE UNIQUE (SPECIES_ID, CODE)
);

CREATE TABLE REQUIREMENT_SET (
    REQUIREMENT_SET_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    SPECIES_ID      BIGINT NOT NULL,
    STAGE_ID        BIGINT NOT NULL,
    NAME            VARCHAR(128) NOT NULL,
    SEX             VARCHAR(16),
    BREED           VARCHAR(64),
    PRODUCTION_LEVEL VARCHAR(32),
    PRODUCTION_VALUE DECIMAL(12, 4),
    PRODUCTION_UNIT VARCHAR(32),
    BODY_WEIGHT_KG  DECIMAL(9, 3),
    PREGNANCY_STATUS VARCHAR(32),
    HOUSING         VARCHAR(64),
    ENVIRONMENT     VARCHAR(64),
    ACTIVITY_LEVEL  VARCHAR(32),
    SOURCE          VARCHAR(64),
    NOTES           VARCHAR(512),
    ACTIVE          SMALLINT NOT NULL DEFAULT 1,
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_REQ_SET PRIMARY KEY (REQUIREMENT_SET_ID),
    CONSTRAINT FK_REQSET_SPECIES FOREIGN KEY (SPECIES_ID) REFERENCES ANIMAL_SPECIES (SPECIES_ID),
    CONSTRAINT FK_REQSET_STAGE FOREIGN KEY (STAGE_ID) REFERENCES ANIMAL_STAGE (STAGE_ID)
);

CREATE INDEX IX_REQSET_LOOKUP ON REQUIREMENT_SET (SPECIES_ID, STAGE_ID, SEX, PRODUCTION_LEVEL, BREED, HOUSING, ENVIRONMENT);

CREATE TABLE REQUIREMENT_LINE (
    REQUIREMENT_LINE_ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    REQUIREMENT_SET_ID BIGINT NOT NULL,
    NUTRIENT_ID     BIGINT NOT NULL,
    MIN_VALUE       DECIMAL(18, 8),
    MAX_VALUE       DECIMAL(18, 8),
    TARGET_VALUE    DECIMAL(18, 8),
    CONSTRAINT PK_REQ_LINE PRIMARY KEY (REQUIREMENT_LINE_ID),
    CONSTRAINT FK_REQLINE_SET FOREIGN KEY (REQUIREMENT_SET_ID) REFERENCES REQUIREMENT_SET (REQUIREMENT_SET_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REQLINE_NUT FOREIGN KEY (NUTRIENT_ID) REFERENCES NUTRIENT (NUTRIENT_ID),
    CONSTRAINT UQ_REQLINE UNIQUE (REQUIREMENT_SET_ID, NUTRIENT_ID)
);

CREATE TABLE FORMULA (
    FORMULA_ID      BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODE            VARCHAR(32),
    NAME            VARCHAR(128) NOT NULL,
    CLIENT_ID       BIGINT,
    SPECIES_ID      BIGINT NOT NULL,
    STAGE_ID        BIGINT NOT NULL,
    REQUIREMENT_SET_ID BIGINT,
    ANIMAL_AGE_DAYS INTEGER,
    SEX             VARCHAR(16),
    BREED           VARCHAR(64),
    PRODUCTION_LEVEL VARCHAR(32),
    HOUSING         VARCHAR(64),
    ENVIRONMENT     VARCHAR(64),
    BATCH_WEIGHT_KG DECIMAL(18, 6) NOT NULL DEFAULT 1000,
    TOTAL_COST      DECIMAL(18, 6),
    COST_PER_KG     DECIMAL(18, 6),
    OPTIMIZATION_TYPE VARCHAR(16) NOT NULL,
    SOLVER_STATUS   VARCHAR(32) NOT NULL,
    OBJECTIVE_VALUE DECIMAL(18, 8),
    NOTES           VARCHAR(512),
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_FORMULA PRIMARY KEY (FORMULA_ID),
    CONSTRAINT FK_FORMULA_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
    CONSTRAINT FK_FORMULA_SPECIES FOREIGN KEY (SPECIES_ID) REFERENCES ANIMAL_SPECIES (SPECIES_ID),
    CONSTRAINT FK_FORMULA_STAGE FOREIGN KEY (STAGE_ID) REFERENCES ANIMAL_STAGE (STAGE_ID),
    CONSTRAINT FK_FORMULA_REQSET FOREIGN KEY (REQUIREMENT_SET_ID) REFERENCES REQUIREMENT_SET (REQUIREMENT_SET_ID)
);

CREATE INDEX IX_FORMULA_CLIENT ON FORMULA (CLIENT_ID, CREATED_AT);
CREATE INDEX IX_FORMULA_ANIMAL ON FORMULA (SPECIES_ID, STAGE_ID, ANIMAL_AGE_DAYS);

CREATE TABLE FORMULA_INGREDIENT (
    FORMULA_ID      BIGINT NOT NULL,
    INGREDIENT_ID   BIGINT NOT NULL,
    INCLUSION_FRAC  DECIMAL(18, 10) NOT NULL,
    AMOUNT_KG       DECIMAL(18, 6) NOT NULL,
    PRICE_USED      DECIMAL(18, 6) NOT NULL,
    COST            DECIMAL(18, 6) NOT NULL,
    CONSTRAINT PK_FORM_ING PRIMARY KEY (FORMULA_ID, INGREDIENT_ID),
    CONSTRAINT FK_FORMING_FORM FOREIGN KEY (FORMULA_ID) REFERENCES FORMULA (FORMULA_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FORMING_ING FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT (INGREDIENT_ID)
);

CREATE TABLE FORMULA_NUTRIENT (
    FORMULA_ID      BIGINT NOT NULL,
    NUTRIENT_ID     BIGINT NOT NULL,
    ACHIEVED_VALUE  DECIMAL(18, 8) NOT NULL,
    MIN_VALUE       DECIMAL(18, 8),
    MAX_VALUE       DECIMAL(18, 8),
    TARGET_VALUE    DECIMAL(18, 8),
    CONSTRAINT PK_FORM_NUT PRIMARY KEY (FORMULA_ID, NUTRIENT_ID),
    CONSTRAINT FK_FORMNUT_FORM FOREIGN KEY (FORMULA_ID) REFERENCES FORMULA (FORMULA_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FORMNUT_NUT FOREIGN KEY (NUTRIENT_ID) REFERENCES NUTRIENT (NUTRIENT_ID)
);
