-- Optional seed data for IBM i after schema-ibmi.sql.
-- For the local H2 profile, Hibernate creates tables and this file is also loaded.

INSERT INTO NUTRIENT (CODE, NAME, UNIT, CATEGORY, DESCRIPTION, ACTIVE) VALUES
('DM', 'Dry Matter', '%', 'PROXIMATE', 'Dry matter content', 1),
('CP', 'Crude Protein', '%', 'PROTEIN', 'Crude protein', 1),
('ME', 'Metabolizable Energy', 'kcal/kg', 'ENERGY', 'Metabolizable energy', 1),
('NEL', 'Net Energy Lactation', 'Mcal/kg', 'ENERGY', 'Net energy for lactation', 1),
('NDF', 'Neutral Detergent Fiber', '%', 'FIBER', 'NDF', 1),
('ADF', 'Acid Detergent Fiber', '%', 'FIBER', 'ADF', 1),
('EE', 'Ether Extract (Fat)', '%', 'FAT', 'Crude fat', 1),
('CA', 'Calcium', '%', 'MINERAL', 'Calcium', 1),
('P', 'Phosphorus', '%', 'MINERAL', 'Total phosphorus', 1),
('K', 'Potassium', '%', 'MINERAL', 'Potassium', 1),
('NA', 'Sodium', '%', 'MINERAL', 'Sodium', 1),
('MG', 'Magnesium', '%', 'MINERAL', 'Magnesium', 1),
('SALT', 'Salt', '%', 'MINERAL', 'Sodium chloride', 1),
('LYS', 'Lysine', '%', 'AMINO_ACID', 'Total lysine', 1),
('MET', 'Methionine', '%', 'AMINO_ACID', 'Total methionine', 1),
('THR', 'Threonine', '%', 'AMINO_ACID', 'Total threonine', 1),
('CA_P', 'Calcium to Phosphorus Ratio', 'ratio', 'RATIO', 'Ca:P ratio target helper', 1);

INSERT INTO ANIMAL_SPECIES (CODE, NAME, DESCRIPTION, ACTIVE) VALUES
('CATTLE', 'Cattle', 'Dairy and beef cattle', 1),
('SWINE', 'Swine', 'Pigs', 1),
('POULTRY', 'Poultry', 'Broilers, layers, turkeys', 1),
('EQUINE', 'Equine', 'Horses', 1),
('SHEEP', 'Sheep', 'Sheep', 1),
('GOAT', 'Goat', 'Goats', 1);

INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'CALF', 'Calf', 0, 90, 40, 120, 'Pre-weaned and early post-weaned calf', 1 FROM ANIMAL_SPECIES WHERE CODE = 'CATTLE';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'GROWING', 'Growing Heifer', 91, 365, 120, 400, 'Growing replacement heifer', 1 FROM ANIMAL_SPECIES WHERE CODE = 'CATTLE';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'LACTATING', 'Lactating Cow', 700, 4000, 500, 800, 'Lactating dairy cow', 1 FROM ANIMAL_SPECIES WHERE CODE = 'CATTLE';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'STARTER', 'Starter', 21, 70, 6, 25, 'Weaned pig starter', 1 FROM ANIMAL_SPECIES WHERE CODE = 'SWINE';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'GROWER', 'Grower', 71, 120, 25, 60, 'Grower pig', 1 FROM ANIMAL_SPECIES WHERE CODE = 'SWINE';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'FINISHER', 'Finisher', 121, 200, 60, 130, 'Finishing pig', 1 FROM ANIMAL_SPECIES WHERE CODE = 'SWINE';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'BROILER_ST', 'Broiler Starter', 0, 14, 0.04, 0.45, 'Broiler starter', 1 FROM ANIMAL_SPECIES WHERE CODE = 'POULTRY';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'BROILER_GR', 'Broiler Grower', 15, 28, 0.45, 1.5, 'Broiler grower', 1 FROM ANIMAL_SPECIES WHERE CODE = 'POULTRY';
INSERT INTO ANIMAL_STAGE (SPECIES_ID, CODE, NAME, AGE_MIN_DAYS, AGE_MAX_DAYS, WEIGHT_MIN_KG, WEIGHT_MAX_KG, DESCRIPTION, ACTIVE)
SELECT SPECIES_ID, 'BROILER_FN', 'Broiler Finisher', 29, 49, 1.5, 3.5, 'Broiler finisher', 1 FROM ANIMAL_SPECIES WHERE CODE = 'POULTRY';

INSERT INTO CLIENT (CODE, NAME, NOTES, IS_DEFAULT, ACTIVE)
SELECT 'DEFAULT', 'Default (general formulas)',
       'Owner for catalog formulas shared across clients', 1, 1
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM CLIENT WHERE CODE = 'DEFAULT');

INSERT INTO CLIENT (CODE, NAME, CONTACT_NAME, PHONE, EMAIL, CITY, STATE, COUNTRY, IS_DEFAULT, ACTIVE) VALUES
('DEMO01', 'Demo Dairy LLC', 'Maria Lopez', '555-0100', 'maria@demodairy.example', 'Ames', 'IA', 'USA', 0, 1),
('DEMO02', 'Prairie Swine Co', 'James Chen', '555-0101', 'james@prairieswine.example', 'Sioux Falls', 'SD', 'USA', 0, 1);

INSERT INTO INGREDIENT (CODE, NAME, CATEGORY, PRICE, PRICE_UNIT, DRY_MATTER_PCT, MIN_INCLUSION, MAX_INCLUSION, QUADRATIC_COST, SUPPLIER, ACTIVE) VALUES
('CORN', 'Corn grain', 'ENERGY', 0.22, 'USD/kg', 86.0, 0, 0.70, 0.02, 'Local elevator', 1),
('SBM48', 'Soybean meal 48%', 'PROTEIN', 0.48, 'USD/kg', 89.0, 0, 0.40, 0.04, 'Crush plant', 1),
('WHEATBR', 'Wheat bran', 'FIBER', 0.18, 'USD/kg', 89.0, 0, 0.25, 0.01, 'Mill', 1),
('ALFALFA', 'Alfalfa hay', 'FORAGE', 0.26, 'USD/kg', 90.0, 0, 0.50, 0.01, 'Hay market', 1),
('CORNSIL', 'Corn silage', 'FORAGE', 0.08, 'USD/kg', 35.0, 0, 0.55, 0.005, 'On farm', 1),
('SOYOIL', 'Soybean oil', 'FAT', 1.10, 'USD/kg', 99.0, 0, 0.06, 0.20, 'Crush plant', 1),
('LIMEST', 'Limestone', 'MINERAL', 0.06, 'USD/kg', 99.0, 0, 0.04, 0.00, 'Mineral supplier', 1),
('DICAL', 'Dicalcium phosphate', 'MINERAL', 0.55, 'USD/kg', 96.0, 0, 0.03, 0.00, 'Mineral supplier', 1),
('SALT', 'Salt', 'MINERAL', 0.12, 'USD/kg', 99.0, 0, 0.02, 0.00, 'Mineral supplier', 1),
('PREMIX', 'Vitamin/mineral premix', 'PREMIX', 2.40, 'USD/kg', 98.0, 0.002, 0.01, 0.00, 'Premix mill', 1),
('BARLEY', 'Barley grain', 'ENERGY', 0.24, 'USD/kg', 88.0, 0, 0.40, 0.02, 'Local elevator', 1),
('FISHML', 'Fish meal', 'PROTEIN', 1.35, 'USD/kg', 92.0, 0, 0.08, 0.10, 'Import', 1);

-- Nutrient composition is as-fed percent or kcal/kg.
-- Helper inserts keyed by codes.

-- Full ingredient x nutrient matrix, then overlay known amounts.
INSERT INTO INGREDNUT (INGREDIENT_ID, NUTRIENT_ID, AMOUNT)
SELECT I.INGREDIENT_ID, N.NUTRIENT_ID, 0
FROM INGREDIENT I
CROSS JOIN NUTRIENT N;

MERGE INTO INGREDNUT T
USING (
    SELECT I.INGREDIENT_ID, N.NUTRIENT_ID, V.A AS AMOUNT
    FROM (
        SELECT 'CORN' C, 'DM' N, 86.0 A FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'CP', 8.3 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'ME', 3350 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'NEL', 1.98 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'NDF', 9.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'ADF', 3.4 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'EE', 3.6 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'CA', 0.03 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'P', 0.28 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'LYS', 0.24 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORN', 'MET', 0.17 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'DM', 89.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'CP', 47.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'ME', 2450 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'NEL', 2.10 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'NDF', 9.8 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'ADF', 6.1 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'EE', 1.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'CA', 0.35 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'P', 0.69 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'LYS', 2.96 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 'MET', 0.67 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'DM', 89.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'CP', 15.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'ME', 2300 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'NEL', 1.54 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'NDF', 42.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'ADF', 13.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'EE', 4.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'CA', 0.13 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'P', 1.18 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'WHEATBR', 'LYS', 0.64 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'DM', 90.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'CP', 18.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'ME', 2100 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'NEL', 1.30 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'NDF', 42.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'ADF', 32.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'EE', 2.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'CA', 1.40 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 'P', 0.24 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'DM', 35.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'CP', 8.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'ME', 1050 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'NEL', 0.72 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'NDF', 45.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'ADF', 26.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'CA', 0.25 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 'P', 0.22 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SOYOIL', 'DM', 99.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SOYOIL', 'CP', 0.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SOYOIL', 'ME', 8800 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SOYOIL', 'NEL', 5.65 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SOYOIL', 'EE', 99.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'LIMEST', 'DM', 99.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'LIMEST', 'CA', 38.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'LIMEST', 'P', 0.02 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'DICAL', 'DM', 96.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'DICAL', 'CA', 22.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'DICAL', 'P', 19.3 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SALT', 'DM', 99.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SALT', 'NA', 39.3 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SALT', 'SALT', 100.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'PREMIX', 'DM', 98.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'DM', 88.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'CP', 11.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'ME', 3050 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'NEL', 1.86 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'NDF', 18.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'EE', 2.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'CA', 0.06 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'P', 0.35 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'BARLEY', 'LYS', 0.40 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'DM', 92.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'CP', 62.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'ME', 3100 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'EE', 9.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'CA', 5.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'P', 3.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'LYS', 4.80 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'FISHML', 'MET', 1.70 FROM SYSIBM.SYSDUMMY1
    ) V
    JOIN INGREDIENT I ON I.CODE = V.C
    JOIN NUTRIENT N ON N.CODE = V.N
) S
ON T.INGREDIENT_ID = S.INGREDIENT_ID AND T.NUTRIENT_ID = S.NUTRIENT_ID
WHEN MATCHED THEN UPDATE SET AMOUNT = S.AMOUNT, UPDATED_AT = CURRENT_TIMESTAMP;

INSERT INTO REQUIREMENT_SET (SPECIES_ID, STAGE_ID, NAME, SEX, BREED, PRODUCTION_LEVEL, PRODUCTION_VALUE, PRODUCTION_UNIT, BODY_WEIGHT_KG, HOUSING, ENVIRONMENT, SOURCE, ACTIVE)
SELECT S.SPECIES_ID, ST.STAGE_ID, 'Dairy lactating high, Holstein, free stall, temperate',
       'F', 'Holstein', 'HIGH', 40, 'kg milk/d', 650, 'FREE_STALL', 'TEMPERATE', 'NRC-like demo', 1
FROM ANIMAL_SPECIES S
JOIN ANIMAL_STAGE ST ON ST.SPECIES_ID = S.SPECIES_ID AND ST.CODE = 'LACTATING'
WHERE S.CODE = 'CATTLE';

INSERT INTO REQUIREMENT_SET (SPECIES_ID, STAGE_ID, NAME, SEX, BREED, PRODUCTION_LEVEL, BODY_WEIGHT_KG, HOUSING, ENVIRONMENT, SOURCE, ACTIVE)
SELECT S.SPECIES_ID, ST.STAGE_ID, 'Swine grower mixed, confinement, temperate',
       'MIXED', 'Commercial', 'MEDIUM', 40, 'CONFINEMENT', 'TEMPERATE', 'NRC-like demo', 1
FROM ANIMAL_SPECIES S
JOIN ANIMAL_STAGE ST ON ST.SPECIES_ID = S.SPECIES_ID AND ST.CODE = 'GROWER'
WHERE S.CODE = 'SWINE';

INSERT INTO REQUIREMENT_SET (SPECIES_ID, STAGE_ID, NAME, SEX, BREED, PRODUCTION_LEVEL, HOUSING, ENVIRONMENT, SOURCE, ACTIVE)
SELECT S.SPECIES_ID, ST.STAGE_ID, 'Broiler grower mixed, confinement, temperate',
       'MIXED', 'Commercial', 'HIGH', 'CONFINEMENT', 'TEMPERATE', 'NRC-like demo', 1
FROM ANIMAL_SPECIES S
JOIN ANIMAL_STAGE ST ON ST.SPECIES_ID = S.SPECIES_ID AND ST.CODE = 'BROILER_GR'
WHERE S.CODE = 'POULTRY';

INSERT INTO REQUIREMENT_LINE (REQUIREMENT_SET_ID, NUTRIENT_ID, MIN_VALUE, MAX_VALUE, TARGET_VALUE)
SELECT RS.REQUIREMENT_SET_ID, N.NUTRIENT_ID, V.MINV, V.MAXV, V.TGT
FROM REQUIREMENT_SET RS
JOIN ANIMAL_SPECIES S ON S.SPECIES_ID = RS.SPECIES_ID
JOIN ANIMAL_STAGE ST ON ST.STAGE_ID = RS.STAGE_ID
JOIN (
    SELECT 'CATTLE' SP, 'LACTATING' STG, 'CP' NC, 16.5 MINV, 18.5 MAXV, 17.5 TGT FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CATTLE', 'LACTATING', 'NEL', 1.55, 1.75, 1.65 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CATTLE', 'LACTATING', 'NDF', 28.0, 40.0, 32.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CATTLE', 'LACTATING', 'CA', 0.65, 1.10, 0.80 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CATTLE', 'LACTATING', 'P', 0.35, 0.55, 0.40 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CATTLE', 'LACTATING', 'EE', 3.0, 6.5, 4.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SWINE', 'GROWER', 'CP', 16.0, 20.0, 18.0 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SWINE', 'GROWER', 'ME', 3200, 3400, 3300 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SWINE', 'GROWER', 'LYS', 0.95, 1.20, 1.05 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SWINE', 'GROWER', 'CA', 0.60, 0.90, 0.70 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SWINE', 'GROWER', 'P', 0.50, 0.70, 0.55 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'POULTRY', 'BROILER_GR', 'CP', 19.0, 22.0, 20.5 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'POULTRY', 'BROILER_GR', 'ME', 3000, 3200, 3100 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'POULTRY', 'BROILER_GR', 'LYS', 1.05, 1.30, 1.15 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'POULTRY', 'BROILER_GR', 'MET', 0.45, 0.60, 0.50 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'POULTRY', 'BROILER_GR', 'CA', 0.80, 1.10, 0.90 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'POULTRY', 'BROILER_GR', 'P', 0.40, 0.65, 0.45 FROM SYSIBM.SYSDUMMY1
) V ON V.SP = S.CODE AND V.STG = ST.CODE
JOIN NUTRIENT N ON N.CODE = V.NC;

-- Preexisting non-optimized (PREFIXED) general formula on the DEFAULT client.
INSERT INTO FORMULA (CODE, NAME, CLIENT_ID, STATUS, SPECIES_ID, STAGE_ID, REQUIREMENT_SET_ID,
                     ANIMAL_AGE_DAYS, SEX, BREED, PRODUCTION_LEVEL, HOUSING, ENVIRONMENT,
                     BATCH_WEIGHT_KG, TOTAL_COST, COST_PER_KG, OPTIMIZATION_TYPE, SOLVER_STATUS, NOTES)
SELECT 'PFX-LAC-1', 'Prefixed lactating mix',
       C.CLIENT_ID, 'PREFIXED', S.SPECIES_ID, ST.STAGE_ID, RS.REQUIREMENT_SET_ID,
       1200, 'F', 'Holstein', 'HIGH', 'FREE_STALL', 'TEMPERATE',
       1000, 248.40, 0.248400, 'NONE', 'NONE', 'Hand-built catalog formula'
FROM CLIENT C
JOIN ANIMAL_SPECIES S ON S.CODE = 'CATTLE'
JOIN ANIMAL_STAGE ST ON ST.SPECIES_ID = S.SPECIES_ID AND ST.CODE = 'LACTATING'
JOIN REQUIREMENT_SET RS ON RS.SPECIES_ID = S.SPECIES_ID AND RS.STAGE_ID = ST.STAGE_ID
WHERE C.CODE = 'DEFAULT';

INSERT INTO FORMULA_INGREDIENT (FORMULA_ID, INGREDIENT_ID, INCLUSION_FRAC, AMOUNT_KG, PRICE_USED, LAST_PRICE, COST)
SELECT F.FORMULA_ID, I.INGREDIENT_ID, V.FRAC, V.FRAC * 1000, I.PRICE, I.PRICE, (V.FRAC * 1000) * I.PRICE
FROM FORMULA F
JOIN CLIENT C ON C.CLIENT_ID = F.CLIENT_ID AND C.CODE = 'DEFAULT'
JOIN (
    SELECT 'CORN' CODE, 0.42 FRAC FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'SBM48', 0.18 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'ALFALFA', 0.22 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'CORNSIL', 0.16 FROM SYSIBM.SYSDUMMY1 UNION ALL
    SELECT 'PREMIX', 0.02 FROM SYSIBM.SYSDUMMY1
) V ON 1 = 1
JOIN INGREDIENT I ON I.CODE = V.CODE
WHERE F.CODE = 'PFX-LAC-1';

INSERT INTO CLIENT_FORMULAS_HDR
    (FORMULA_ID, CLIENT_ID, FORMULA_DESCRIPTION, LAST_PRICE, ANIMAL_ID, OPTIMIZATION_TECHNIQUE)
SELECT F.FORMULA_ID, F.CLIENT_ID, F.NAME, COALESCE(F.COST_PER_KG, F.TOTAL_COST),
       F.SPECIES_ID, F.OPTIMIZATION_TYPE
FROM FORMULA F
WHERE NOT EXISTS (
    SELECT 1 FROM CLIENT_FORMULAS_HDR H WHERE H.FORMULA_ID = F.FORMULA_ID
);
